name: anisched
description: AniSched
publish_to: 'none'
version: 2.2.2+151

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    retrofit: ^2.0.1
    json_serializable: ^4.1.4
    url_launcher: ^6.0.9
    palette_generator: ^0.3.0
    cupertino_icons: ^1.0.3
    cached_network_image: ^3.1.0
    flutter_cache_manager: ^3.1.2
    package_info_plus: ^1.0.4
    shared_preferences: ^2.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    retrofit_generator: ^2.0.1
    build_runner: ^2.0.6
    msix: ^2.1.3
    
flutter:
    uses-material-design: true
    fonts:
      - family: Noto Sans CJK KR
        fonts: 
            - asset: fonts/NotoSansCJKkr-Light.otf
            - asset: fonts/NotoSansCJKkr-Medium.otf
            - asset: fonts/NotoSansCJKkr-Regular.otf

msix_config:
    display_name: AniSched-Desktop
    publisher_display_name: Novang
    identity_name: 13139Novang.AniSched-Desktop
    publisher: CN=8618EF24-0399-4ACB-BBBC-87A2F5B3B625
    vs_generated_images_folder_path: windows\Assets
    icons_background_color: '#E3567D'
    languages: ko-KR
    msix_version: 2.2.2.0
    architecture: x64
    capabilities: 'internetClient'
    store: true
