name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo ::set-output name=REPO_TAG::$(git describe --tags --abbrev=0)
          echo ::set-output name=REPO_NUM::$(git rev-list --count $(git describe --tags --abbrev=0))
        id: set-up-env-var

      - name: Set up secret files
        run: |
          cd anisched
          echo "class APIKey { static const String TMDB_API_KEY = '${{ secrets.TMDB_API_KEY }}'; }" > ./lib/_API_KEY.dart

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - name: Initialize Flutter SDK
        run: |
          cd anisched
          flutter config --enable-macos-desktop

      - name: Build Project
        run: |
          cd anisched
          flutter build macos --release --pub --build-name=${{ steps.set-up-env-var.outputs.REPO_TAG }} --build-number ${{ steps.set-up-env-var.outputs.REPO_NUM }}

      - uses: actions/setup-node@v2
      - name: Create DMG
        run: |
          npm install -g create-dmg
          create-dmg --identity="${{ secrets.BUILD_CERTIFICATE_IDENTITY }}" ./anisched/build/macos/Build/Products/Release/AniSched.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set-up-env-var.outputs.REPO_TAG }}
          name: ${{ steps.set-up-env-var.outputs.REPO_TAG }}
          files: ./AniSched ${{ steps.set-up-env-var.outputs.REPO_TAG }}.dmg

  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo $('::set-output name=REPO_TAG::' + $(git describe --tags --abbrev=0))
          echo $('::set-output name=REPO_NUM::' + $(git rev-list --count $(git describe --tags --abbrev=0)))
        id: set-up-env-var
        shell: pwsh

      - name: Set up secret files
        run: |
          cd anisched
          echo "class APIKey { static const String TMDB_API_KEY = '${{ secrets.TMDB_API_KEY }}'; }" > ./lib/_API_KEY.dart

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - name: Initialize Flutter SDK
        run: |
          cd anisched
          flutter config --enable-windows-desktop

      - name: Update 'pubspec.yaml' version
        run: |
          (Get-Content .\anisched\pubspec.yaml) -replace '(version: \d.\d.\d\+\d.*)', ("version: {0}+{1}" -f "${{ steps.set-up-env-var.outputs.REPO_TAG }}", "${{ steps.set-up-env-var.outputs.REPO_NUM }}") | Out-File -Encoding 'UTF8' .\anisched\pubspec.yaml
          (Get-Content .\anisched\pubspec.yaml) -replace '(msix_version: \d.\d.\d.\d)', ("msix_version: {0}.0" -f "${{ steps.set-up-env-var.outputs.REPO_TAG }}") | Out-File -Encoding 'UTF8' .\anisched\pubspec.yaml
        shell: pwsh

      - name: Build Project
        run: |
          cd anisched
          flutter build windows --release --pub

      - name: Create MSIX & ZIP
        run: |
          Compress-Archive -Path '.\anisched\build\windows\runner\Release\*' -DestinationPath (".\AniSched.{0}-win.zip" -f "${{ steps.set-up-env-var.outputs.REPO_TAG }}") -CompressionLevel Optimal
          cd anisched
          flutter pub run msix:create --store
          mv ./build/windows/runner/Release/anisched.msix ../AniSched.${{ steps.set-up-env-var.outputs.REPO_TAG }}-win.msix
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set-up-env-var.outputs.REPO_TAG }}
          name: ${{ steps.set-up-env-var.outputs.REPO_TAG }}
          files: |
            ./AniSched.${{ steps.set-up-env-var.outputs.REPO_TAG }}-win.zip
            ./AniSched.${{ steps.set-up-env-var.outputs.REPO_TAG }}-win.msix

          